# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sub-Declaration
version:      0.9
version_from: lib/Sub/Declaration.pm
installdirs:  site
requires:
    Filter::Simple:                0.78
    Lexical::Util:                 0.3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
